# Use official Python image
FROM python:3.10

# Set working directory
WORKDIR /app

# Copy files
COPY pyproject.toml uv.lock ./


# Install dependencies
RUN pip install uv && uv pip install --system .

COPY . .

# Expose port
EXPOSE 8000

# Run FastAPI with uvicorn
CMD ["python", "-m", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]